spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/master
    username: admin
    password: changeme
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true

# https://openrouter.ai/docs/quickstart - Using the OpenRouter API directly
# Mam na koncie $2, więcej nie korzystam, można używać
openrouter:
  api-key: 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