openrouter:
  api-key: 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    # ← Twój OpenAI Project Key
  base-url: https://api.openai.com
  model: gpt-4.1-mini                          # np. ten
  referer:                                     # (puste/usuń, niepotrzebne)
  title:
